- hosts: all
  gather_facts: yes
  become: True
  tasks:
    - name: Hola mundo !!!
      debug:
        msg: Hola mundo
      tags: 
        - saludo
        - bienvenida
      
    - name: Crear usuario
      user:
        name: silvia
        state: present
        
    - name: Caracteristicas de la maquina
      debug: 
        msg: "{{ ansible_facts.distribution }}"
        
    - name: Adios Mundo
      debug: 
        msg: Adios Mundo
      tags:
        - saludo
        - despedida