- hosts: all
  gather_facts: yes
  become: True
  
  tasks:
    - name: Hola mundo !!!
      debug:
        msg: Hola mundo
      tags: 
        - saludo
        - bienvenida
      when: 
        - ansible_facts.distribution == 'CentOS'
      notify: handler1
      
    - name: Crear usuario
      user:
        name: silvia
        state: present
      notify: usuariocreado
      changed_when: False
        
    - name: Caracteristicas de la maquina
      debug: 
        msg: "{{ ansible_facts.distribution }}"
        
    - name: Adios Mundo
      debug: 
        msg: "Adios {{ persona }}""
      tags:
        - saludo
        - despedida
      vars:
        persona: silvia
        
  handlers:
    - name: handler1
      debug: 
        msg: Soy el handler 1
      listen: usuariocreado
    - name: handler2
      debug: 
        msg: soy el handler 2
      listen: usuariocreado
      